### ISSUE TITLE
Add Subcategory of language for Autopilot

### ISSUE THREAD

**Issue by Drinkiiies** [PeterKlapwijk/PowerShell#1]
Hi Peter

This script is super and I have used most of it. Thank you.
I work in Switzerland and we use a "flavor" of the language pack. I couldn't think of a better word, so I went with that.

I guess it's not a very cool solution how I added it, but it works.

```
# The language we want as new default. Language tag can be found here: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows
$language = "de-DE"
# The subcategory of languagepack if needed. set to empty, if not needed.
$languageflavor="de-CH"
# Geographical ID we want to set. GeoID can be found here: https://learn.microsoft.com/en-us/windows/win32/intl/table-of-geographical-locations?redirectedfrom=MSDN
$geoId = "223"  # Switzerland

# Start Transcript
Start-Transcript -Path "$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\$($(Split-Path $PSCommandPath -Leaf).ToLower().Replace(".ps1",".log"))" | Out-Null

# Install an additional language pack including FODs
"Installing languagepack"
Install-Language $language -CopyToSettings

#Check if languageflavor is defined. If yes, replace the lanuage value
if($languageflavor -ne ""){

$language = $languageflavor

}
```

**Comment by PeterKlapwijk** [comment]
Hi @Drinkiiies ,

Sorry for my late response, pretty busy with some other things :)

Do you mean, you install Language pack de-DE, but for all the other set commands you'll set the "flavor"?

Thus you use Install-Language de-DE (use de-DE only once) and for example Set-WinUILanguageOverride -Language de-CH and all the other Set command you use de-CH?

I guess the thing you call flavor, is the ISO code language as listed on for example https://lingohub.com/developers/supported-locales/language-designators-with-regions. And called input locales by Microsoft https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs

Regards,

Peter

**Comment by Drinkiiies** [comment]
Hi Peter

Dont worry about it. I have a tonne of stuff going on myself.

So I remember having to add another line if you want to use a subcategory of a languge. No idea why I called it a "flavor". For Switzerland you download the de-DE language pack and set it to de-CH afterwards.

Like Set-WinUILanguageOverride -Language de-CH? -> exactly that, but your script used the downloaded language for checks etc. afterwards. So for cases like mine you need to have a sceond one that will check and actually install "de-CH".

Just a minor thing I wanted to contribute to something that works really well and makes sense 🙂

Regards,
Michael

________________________________
From: Peter Klapwijk ***@***.***>
Sent: Thursday, 9 February 2023 14:38
To: PeterKlapwijk/PowerShell ***@***.***>
Cc: Kerley Michael ***@***.***>; Mention ***@***.***>
Subject: [Extern]: Re: [PeterKlapwijk/PowerShell] Add Subcategory of language for Autopilot (Issue #1)


Hi @Drinkiiies<https://github.com/Drinkiiies> ,

Sorry for my late response, pretty busy with some other things :)

Do you mean, you install Language pack de-DE, but for all the other set commands you'll set the "flavor"?
Like Set-WinUILanguageOverride -Language de-CH?

Regards,

Peter

**Comment by PeterKlapwijk** [comment]
Hi @Drinkiiies ,

Well your 'minor thing' makes sense, also for other countries.
I think splitting up $language in two variables would be an easy solution. 
Can you send me an email on info @ inthecloud247.com?
I'll make a change in the script, would be nice if you could check if that does make sense to you 😀
Regards,

Peter

**Comment by Drinkiiies** [comment]
Sure 🙂

i'll do it on sunday or monday. I actually dont have access to my stuff at the moment.
Skiing holidays 😉

Regards,
Michael
________________________________
From: Peter Klapwijk ***@***.***>
Sent: Thursday, 9 February 2023 21:17
To: PeterKlapwijk/PowerShell ***@***.***>
Cc: Kerley Michael ***@***.***>; Mention ***@***.***>
Subject: [Extern]: Re: [PeterKlapwijk/PowerShell] Add Subcategory of language for Autopilot (Issue #1)


Hi @Drinkiiies<https://github.com/Drinkiiies> ,

Well your 'minor thing' makes sense, also for other countries.
I think splitting up $language in two variables would be an easy solution.
Can you send me an email on info @ inthecloud247.com?
I'll make a change in the script, would be nice if you could check if that does make sense to you 😀
Regards,

Peter

**Comment by PeterKlapwijk** [comment]
No problem. 
Enjoy you're time off!

**Comment by Drinkiiies** [comment]
oh I shall. Thank you!
________________________________
From: Peter Klapwijk ***@***.***>
Sent: Thursday, 9 February 2023 21:22
To: PeterKlapwijk/PowerShell ***@***.***>
Cc: Kerley Michael ***@***.***>; Mention ***@***.***>
Subject: [Extern]: Re: [PeterKlapwijk/PowerShell] Add Subcategory of language for Autopilot (Issue #1)


No problem.
Enjoy you're time off!

**Comment by PeterKlapwijk** [comment]
@Drinkiiies any chance you can send me an email so I can send you a new version of the script :)

**Comment by Drinkiiies** [comment]
Hi Peter

Sorry, I broke my leg and am currently in hospital. (as one does). I will get back to you next week.

Regards,
Michael

Von: Peter Klapwijk ***@***.***>
Gesendet: Dienstag, 14. Februar 2023 21:05
An: PeterKlapwijk/PowerShell ***@***.***>
Cc: Kerley Michael ***@***.***>; Mention ***@***.***>
Betreff: [Extern]: Re: [PeterKlapwijk/PowerShell] Add Subcategory of language for Autopilot (Issue #1)


@Drinkiiies<https://github.com/Drinkiiies> any chance you can send me an email so I can send you a new version of the script :)

**Comment by PeterKlapwijk** [comment]
Oh no!
All the best and great recovery.

**Comment by Drinkiiies** [comment]
thankyou

Von: Peter Klapwijk ***@***.***>
Gesendet: Mittwoch, 15. Februar 2023 08:22
An: PeterKlapwijk/PowerShell ***@***.***>
Cc: Kerley Michael ***@***.***>; Mention ***@***.***>
Betreff: [Extern]: Re: [PeterKlapwijk/PowerShell] Add Subcategory of language for Autopilot (Issue #1)


Oh no!
All the best and great recovery.

**Comment by PeterKlapwijk** [comment]
Version 1.1 is published which solves this issue.
@Drinkiiies I've asked one of your countrymen to verify the new version and he confirmed this would solve the issue. Let me know how it runs for you.

Regards,

Peter
