### ISSUE TITLE
errors with languages that don't have their own language pack.

### ISSUE THREAD

**Issue by l4m3us3r** [PeterKlapwijk/PowerShell#5]
When I set language to en-NZ, 
$language = "en-NZ"
Install-Language $language -CopyToSettings
Set-SystemPreferredUILanguage $language

both of these powershell commands work, but they install en-GB and set preferred ui lanuage to en-GB.

So I have simply commented out the checks and everything else works as expected:

#if ($installedLanguage -like $language)

#if ($SystemPreferredUILanguage -like $language){

**Comment by PeterKlapwijk** [comment]
Thanks for pointing this out and describing the workaround.
